/*
CHALLENGE ORACLE - PROJETO CLARITI
Disciplina: Smart SQL & Relational Databases
Etapa 2 - Script DDL para implementação do banco de dados

Integrantes:
- Filipe Santos de Oliveira        - RM572828
- Giovanni Pascon Corrêa           - RM571546
- Nicolas Fois Lima                - RM571619
- Vitor Matias do Nascimento       - RM572761
- Yasmin Yumi Tsunokawa            - RM569408
*/
--------------------------------------------------------
--  Arquivo criado - terça-feira-agosto-25-2026   
--------------------------------------------------------
DROP TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO";
--------------------------------------------------------
--  DDL for Table TB_PAINEL_MUNICIPIO_ANO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" 
   (	"CD_MUNICIPIO_RES" VARCHAR2(6 BYTE) COLLATE "USING_NLS_COMP", 
	"NR_ANO" NUMBER(4,0), 
	"QT_POPULACAO" NUMBER(9,0), 
	"NM_MUNICIPIO" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"QT_INTERNACOES_UTI" NUMBER(6,0), 
	"QT_INTERNACOES_ICSAP_UTI" NUMBER(6,0), 
	"VL_TOTAL_UTI" NUMBER(18,2), 
	"QT_DIAS_PERM_UTI" NUMBER(8,0), 
	"QT_ESTABELECIMENTOS_MEDIA" NUMBER(10,2), 
	"QT_LEITOS_EXISTENTES_MEDIA" NUMBER(10,2), 
	"QT_LEITOS_SUS_MEDIA" NUMBER(10,2), 
	"VL_SIOPS_DOTACAO_ATUALIZADA" NUMBER(18,2), 
	"VL_SIOPS_DESPESA_EMPENHADA" NUMBER(18,2), 
	"VL_SIOPS_DESPESA_LIQUIDADA" NUMBER(18,2), 
	"VL_SIOPS_DESPESA_PAGA" NUMBER(18,2)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"."CD_MUNICIPIO_RES" IS 'Codigo IBGE de 6 digitos do municipio.';
   COMMENT ON COLUMN "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"."NR_ANO" IS 'Ano de referencia do registro municipal.';
   COMMENT ON COLUMN "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"."QT_POPULACAO" IS 'Populacao do municipio no ano de referencia, conforme dados do IBGE.';
   COMMENT ON COLUMN "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"."NM_MUNICIPIO" IS 'Nome do municipio conforme identificacao do IBGE.';
   COMMENT ON COLUMN "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"."QT_INTERNACOES_UTI" IS 'Total de internacoes com UTI de residentes do municipio no ano.';
   COMMENT ON COLUMN "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"."QT_INTERNACOES_ICSAP_UTI" IS 'Quantidade de internacoes em UTI classificadas como Condicoes Sensiveis a Atencao Primaria.';
   COMMENT ON COLUMN "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"."VL_TOTAL_UTI" IS 'Valor total pago pelas AIHs das internacoes com UTI do municipio no ano.';
   COMMENT ON COLUMN "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"."QT_DIAS_PERM_UTI" IS 'Soma dos dias de permanencia das internacoes com UTI do municipio no ano.';
   COMMENT ON COLUMN "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"."QT_ESTABELECIMENTOS_MEDIA" IS 'Media mensal de estabelecimentos de saude ativos no municipio no ano.';
   COMMENT ON COLUMN "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"."QT_LEITOS_EXISTENTES_MEDIA" IS 'Media mensal de leitos existentes no municipio no ano.';
   COMMENT ON COLUMN "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"."QT_LEITOS_SUS_MEDIA" IS 'Media mensal de leitos SUS no municipio no ano.';
   COMMENT ON COLUMN "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"."VL_SIOPS_DOTACAO_ATUALIZADA" IS 'Dotacao atualizada de saude do municipio referente ao ano anterior ao desfecho analisado.';
   COMMENT ON COLUMN "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"."VL_SIOPS_DESPESA_EMPENHADA" IS 'Despesa empenhada em saude do municipio referente ao ano anterior ao desfecho analisado.';
   COMMENT ON COLUMN "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"."VL_SIOPS_DESPESA_LIQUIDADA" IS 'Despesa liquidada em saude do municipio referente ao ano anterior ao desfecho analisado.';
   COMMENT ON COLUMN "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"."VL_SIOPS_DESPESA_PAGA" IS 'Despesa efetivamente paga em saude pelo municipio no ano anterior ao desfecho analisado.';
   COMMENT ON TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO"  IS 'Painel anual por municipio de Sao Paulo com populacao, internacoes UTI, ICSAP, capacidade hospitalar e dados de despesas publicas em saude.';
--------------------------------------------------------
--  DDL for Index PK_PAINEL_MUNICIPIO_ANO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_PAINEL_MUNICIPIO_ANO" ON "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" ("CD_MUNICIPIO_RES", "NR_ANO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TB_PAINEL_MUNICIPIO_ANO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" MODIFY ("CD_MUNICIPIO_RES" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" MODIFY ("NR_ANO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" MODIFY ("QT_POPULACAO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" MODIFY ("NM_MUNICIPIO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" MODIFY ("QT_INTERNACOES_UTI" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" MODIFY ("QT_INTERNACOES_ICSAP_UTI" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" MODIFY ("VL_TOTAL_UTI" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" MODIFY ("QT_DIAS_PERM_UTI" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" ADD CONSTRAINT "CK_PAINEL_ANO" CHECK (NR_ANO IN (2022, 2023, 2024)) ENABLE;
  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" ADD CONSTRAINT "CK_PAINEL_POPULACAO" CHECK (QT_POPULACAO >= 0) ENABLE;
  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" ADD CONSTRAINT "CK_PAINEL_INTERNACOES_UTI" CHECK (QT_INTERNACOES_UTI >= 0) ENABLE;
  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" ADD CONSTRAINT "CK_PAINEL_ICSAP_UTI" CHECK (
            QT_INTERNACOES_ICSAP_UTI >= 0
            AND QT_INTERNACOES_ICSAP_UTI <= QT_INTERNACOES_UTI
        ) ENABLE;
  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" ADD CONSTRAINT "CK_PAINEL_VALOR_UTI" CHECK (VL_TOTAL_UTI >= 0) ENABLE;
  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" ADD CONSTRAINT "CK_PAINEL_DIAS_PERM" CHECK (QT_DIAS_PERM_UTI >= 0) ENABLE;
  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" ADD CONSTRAINT "PK_PAINEL_MUNICIPIO_ANO" PRIMARY KEY ("CD_MUNICIPIO_RES", "NR_ANO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_PAINEL_MUNICIPIO_ANO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TB_PAINEL_MUNICIPIO_ANO" ADD CONSTRAINT "FK_PAINEL_MUNICIPIO" FOREIGN KEY ("CD_MUNICIPIO_RES")
	  REFERENCES "ADMIN"."TB_MUNICIPIO" ("CD_MUNICIPIO_RES") ENABLE;
